# -*- coding: utf-8 -*-
"""Pro-105.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJ6C52jH6PX-Nvazqg2_W09ITYc3Z5WM
"""

import math
import csv
from numpy import square
import pandas as pd
import plotly.express as px

with open('data1.csv', newline='') as f:
    reader = csv.reader(f)
    file_data = list(reader)

data = file_data[0]

def mean(data):
    n = len(data)
    total = 0
    for x in data:
        total += int(x)
    
    mean = total/n
    return mean

squared_list = []
for number in data:
    a = int(number) - mean(data)
    a = a**2
    squared_list.append(a)

sum = 0
for i in squared_list:
    sum += i

# divide the sum by the total number of values
result = sum/(len(data)-1)

std_deviation = math.sqrt(result)

print(std_deviation)